import { TrendingNearbyItem } from "./trending-nearby.types";

export const trendingNearbyData: TrendingNearbyItem[] = [
  {
    id: "1",
    name: "Satyam Kumar",
    image: "/body spa bg.jpg",
    avatar: "/massage.webp",
    service: "Swedish Massage",
    availability: "9AM - 6PM",
    distance: "1.2km away",
    organizationId: "store-1",
    rating: 4.8,
    reviews: "120+",
    description:
      "Premium wellness & healing center offering therapeutic massages and holistic treatments tailored to your body's needs.",
    desktopService: "Swedish Massage",
    desktopServices: [
      { label: "Hairs", price: "$80" },
      { label: "Deep Tissue", price: "$20" },
      { label: "Flexible", price: "$10" },
      { label: "Aromatherapy", price: "$25" },
    ],
  },
  {
    id: "2",
    name: "Lori Massage Parlour",
    image: "/massage.webp",
    avatar: "/body spa bg.jpg",
    service: "Deep Tissue Massage",
    availability: "9AM - 5PM",
    distance: "1.2km away",
    organizationId: "org-trending-2",
    rating: 4.8,
    reviews: "120+",
    description:
      "Premium wellness & healing center offering therapeutic massages and holistic treatments tailored to your body's needs.",
    desktopService: "Swedish Massage",
    desktopServices: [
      { label: "Hairs", price: "$80" },
      { label: "Deep Tissue", price: "$20" },
      { label: "Flexible", price: "$10" },
      { label: "Aromatherapy", price: "$25" },
    ],
  },
  {
    id: "3",
    name: "Satyam Kumar",
    image: "/body spa bg.jpg",
    avatar: "/massage.webp",
    service: "Swedish Massage",
    availability: "9AM - 6PM",
    distance: "1.2km away",
    organizationId: "store-1",
    rating: 4.8,
    reviews: "120+",
    description:
      "Premium wellness & healing center offering therapeutic massages and holistic treatments tailored to your body's needs.",
    desktopService: "Swedish Massage",
    desktopServices: [
      { label: "Hairs", price: "$80" },
      { label: "Deep Tissue", price: "$20" },
      { label: "Flexible", price: "$10" },
      { label: "Aromatherapy", price: "$25" },
    ],
  },
  {
    id: "4",
    name: "Satyam Kumar",
    image: "/body spa bg.jpg",
    avatar: "/massage.webp",
    service: "Swedish Massage",
    availability: "9AM - 6PM",
    distance: "1.2km away",
    organizationId: "store-3",
    rating: 4.8,
    reviews: "120+",
    description:
      "Premium wellness & healing center offering therapeutic massages and holistic treatments tailored to your body's needs.",
    desktopService: "Swedish Massage",
    desktopServices: [
      { label: "Hairs", price: "$80" },
      { label: "Deep Tissue", price: "$20" },
      { label: "Flexible", price: "$10" },
      { label: "Aromatherapy", price: "$25" },
    ],
  },
  {
    id: "5",
    name: "Satyam Kumar",
    image: "/body spa bg.jpg",
    avatar: "/massage.webp",
    service: "Swedish Massage",
    availability: "9AM - 6PM",
    distance: "1.2km away",
    organizationId: "store-2",
    rating: 4.8,
    reviews: "120+",
    description:
      "Premium wellness & healing center offering therapeutic massages and holistic treatments tailored to your body's needs.",
    desktopService: "Swedish Massage",
    desktopServices: [
      { label: "Hairs", price: "$80" },
      { label: "Deep Tissue", price: "$20" },
      { label: "Flexible", price: "$10" },
      { label: "Aromatherapy", price: "$25" },
    ],
  },
];
